### ISSUE TITLE
Export Vertical formatting

### ISSUE THREAD

**Issue by sporto** [dillonkearns/elm-graphql#107]
I often find myself opening generated files to see what is available and how can it be used.

In https://github.com/dillonkearns/elm-graphql/issues/74 formatting of some type aliases was changed to allow better readability.

This is very helpful.

I often open generated files to see what things are available by looking at the exports.
But is hard to read the exports when they are in one line (when there are many):

```
module Api.Object.Reports exposing (BudgetRemainingForCurrentFinancialYearRequiredArguments, BudgetRemainingForCurrentMonthRequiredArguments, ...)
```

Formatting with breaks would make reading much easier:

```
module Api.Object.Reports exposing 
   ( BudgetRemainingForCurrentFinancialYearRequiredArguments
   , BudgetRemainingForCurrentMonthRequiredArguments
   , BudgetRemainingForCurrentWeekRequiredArguments
   , ...)
```

Thanks

**Comment by dillonkearns** [comment]
👍The same thing has crossed my mind, seems like a good improvement. I'll go ahead and change that when I have some spare cycles. Thanks!

**Comment by sporto** [comment]
Latest version of elm-format generates `module Api.Mutation exposing (..)`
So this issue is not relevant anymore
