### ISSUE TITLE
Npm can't show the readme

### ISSUE THREAD

**Issue by Razzeee** [dillonkearns/elm-graphql#110]
Not much to add, never seen this before

https://www.npmjs.com/package/@dillonkearns/elm-graphql

**Comment by dillonkearns** [comment]
Hmm, very strange indeed. It looks like it worked on version 3.0.1 and then stopped with the 3.1.0 changes. I'll examine the diff.

https://www.npmjs.com/package/@dillonkearns/elm-graphql/v/3.0.1

**Comment by dillonkearns** [comment]
🤷‍♂ well... it seems like it's working now? I'll just consider it a fluke unless I see it happen again. Thanks for opening the issue!
