### ISSUE TITLE
Support http 3.0

### ISSUE THREAD

**Issue by aaahrens** [dillonkearns/elm-graphql#112]
Hi, I know 3.0 landed a short while ago, but I LOVE the new Task focus in the http package and it would be great if you supported it. Fantastic library <3

**Comment by sporto** [comment]
I couldn't find a v3 of http, link?

**Comment by dillonkearns** [comment]
Yes, I'm also curious what you have in mind @aaahrens! A link would be super helpful.

If you're referring to the new interface in the `elm/http@2.0.0` package, I believe I've captured the relevant changes to the API with the following:

* [`Graphql.Http.sendWithTracker`](https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-Http#sendWithTracker)
* [The `Graphql.Http.HttpError` type](https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-Http#HttpError)


And there's already a function for [`Graphql.Http.toTask`](https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-Http#toTask).

Please point us to the relevant functions that you have in mind to help us understanding what you had in mind 😄 And very glad to hear you're enjoying the library!

**Comment by aaahrens** [comment]
holy crap it's gone. It was there like two days ago <.< maybe someone pushed a new version by accident. I'm not crazy I promise.
