### ISSUE TITLE
InputObjects incorrect loop detection with List and 2 levels of nesting

### ISSUE THREAD

**Issue by mattdb** [dillonkearns/elm-graphql#138]
The following GraphQL schema results in the `GroupInput` object being wrapped for circular reference protection (`GroupInput GroupInputRaw`):

```GraphQL
type Mutation {
  createGroup(groupInput: GroupInput!): String
}

input GroupInput {
  products: [ProductInputNewOrId!]
}
input ProductInputNewOrId {
  newProduct: ProductInput
}
input ProductInput {
  name: String!
}

type Query {
  hello: String
}
```

I believe this is close to the minimum required to duplicate:

- If the `products` field of `GroupInput` is changed to take a single `ProductInputNewOrId!`, no loop is detected (correctly).
- if `newProduct` field of `ProductInputNewOrId` is set to `String!`, no loop is detected (correctly)

I _think_ the following test case duplicates the above scenario (in [InputObjectLoopsTests.elm](https://github.com/dillonkearns/elm-graphql/blob/master/generator/tests/Generator/InputObjectLoopsTests.elm)):

```elm
        , test "deeply nested through list non-circular" <|
            \() ->
                [ TypeDefinition (ClassCaseName.build "GroupInput")
                    (InputObjectType [ fieldListRef "ProductInputNewOrId" "products" ])
                    Nothing
                , TypeDefinition (ClassCaseName.build "ProductInputNewOrId")
                    (InputObjectType [ field "ProductInput" "newProduct" ])
                    Nothing
                , TypeDefinition (ClassCaseName.build "ProductInput")
                    (InputObjectType [ scalarField "name" ])
                    Nothing
                ]
                    |> InputObjectLoops.any
                    |> Expect.equal False

-- ...

scalarField : String -> Field
scalarField fieldName =
    { name = CamelCaseName.build fieldName
    , description = Nothing
    , typeRef = TypeReference (Scalar Scalar.String) NonNullable
    , args = []
    }

```

**Comment by dillonkearns** [comment]
Thank you so much for the minimal failing test case @mattdb! I appreciate you taking the time to report and reproduce the issue!

It's all fixed now, see [npm package @dillonkearns/elm-graphql@3.6.0](https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-NPM-PACKAGE.md#360---2018-05-17)
