### ISSUE TITLE
tree-sitter-elm failing to parse one of generator files

### ISSUE THREAD

**Issue by buinauskas** [dillonkearns/elm-graphql#167]
Hello!

I'm looking for working Elm code and running tests against `tree-sitter-elm` to validate parser. One of tests have failed at https://github.com/dillonkearns/elm-graphql/blob/master/generator/src/Graphql/Generator/ScalarCodecs.elm#L71

Is there some magic happening or that function really has invalid syntax?

Thanks! :)

**Comment by dillonkearns** [comment]
It's just valid syntax! A little strange, but you can have an empty string, i.e. `""`, within a triple quote and it's perfectly valid:

```elm
"""
    ""
"""
```

My code gen code here, like this module, uses triple quotes all over the place to hard code pieces of elm code. So the `""` is just an empty String within the elm code its generating. The triple quote doesn't terminate until it sees another triple quote, so it's perfectly valid.

**Comment by buinauskas** [comment]
Awesome! Thank you very much for explaining this 👍🙂
