### ISSUE TITLE
Pre-execution error responses not supported

### ISSUE THREAD

**Issue by ronanyeah** [dillonkearns/elm-graphql#168]
According to the [response spec](https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md#response-format):
> If the operation included execution, the response map must contain an entry with key data. The value of this entry is described in the “Data” section. If the operation failed before execution, due to a syntax error, missing information, or validation error, this entry must not be present.

I'm seeing that a response without a data field is failing to decode for me however, such as this from Hasura:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "data-exception"
      },
      "message": "invalid input syntax for type uuid: \"7fcd8241-a310-4463-8a8b-974953a8151-\""
    }
  ]
}
```

Seems like adding this:
```
GraphqlError.decoder
    |> Json.Decode.map
        (\errs ->
            Err ( GraphqlError.UnparsedData Json.Encode.null, errs )
        )
```
somewhere around [here](https://github.com/dillonkearns/elm-graphql/blob/f39a4cbbab258ee6d37a128a2647d003c7a366e9/src/Graphql/Http.elm#L620) would do the trick!

**Comment by dillonkearns** [comment]
Should be all good now, thanks for the details on the issue Ronan!

**Comment by ronanyeah** [comment]
Much appreciated, thank you.
