### ISSUE TITLE
Consideration to support GraphQL Queries/Mutations/Subscriptions from JS code

### ISSUE THREAD

**Issue by nick-walt** [dillonkearns/elm-graphql#202]
I was wondering if this is a feasible proposition but it does seem like a good way to improve interop between Elm and JS.

Essentially, this capability would mean that GraphQL could be used in place of JSON - for those who can't use Typescript and have control over the JS code.

I don't know if Elm would need to become a full GraphQL endpoint (server) or if it just needs to apply Decoding for GraphQL incoming from JS,

So the step would be:
 - if already using elm-graphql to make requests also use elm-graphql to receive requests
 - if already using typescript step up to using elm-typescript-interop

There is something really appealing about using the same library for both making and receiving GraphQL requests.

**Comment by dillonkearns** [comment]
Hi Nick, I appreciate the suggestion, but I think this is outside of the intended use of GraphQL. It's also outside of the scope of this project, and I prefer lightweight solutions like using TypeScript type declarations since they have fewer moving parts and better support.

Best,

Dillon
