### ISSUE TITLE
Api files can't find the Graphqelm modules

### ISSUE THREAD

**Issue by john-law** [dillonkearns/elm-graphql#204]
My auto generated API files can't find the Graphqelm modules. The first error the parser finds is:

> import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
I was expecting to see the (..) symbol.

If I comment the line I just get "can't find module" errors on the subsequent imports.

Solutions I tried:
- Deleting and creating the elm-stuff again

My elm.json is the following:

``` js
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "dillonkearns/elm-graphql": "4.3.1",
            "elm/browser": "1.0.1",
            "elm/core": "1.0.2",
            "elm/html": "1.0.0",
            "elm/http": "2.0.0",
            "elm/json": "1.1.3"
        },
        "indirect": {
            "Skinney/murmur3": "2.0.8",
            "elm/bytes": "1.0.8",
            "elm/file": "1.0.5",
            "elm/regex": "1.0.0",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2",
            "elm-community/list-extra": "8.2.2",
            "lukewestby/elm-string-interpolate": "1.0.4"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}
```

**Comment by dillonkearns** [comment]
Graphqelm is the old name of the library, so it looks like you are using an old version of the CLI.

Using the latest elm package and NPM package will resolve your issue.
