### ISSUE TITLE
Fix typo in generated code

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-graphql#218]
<img width="428" alt="Screenshot 2019-10-01 at 13 55 44" src="https://user-images.githubusercontent.com/1384166/65972102-2efd1300-e41e-11e9-9f8e-11c407b4b743.png">

exhuastive -> exhaustive

**Comment by dillonkearns** [comment]
Fixed by https://github.com/dillonkearns/elm-graphql/commit/8a1b1c2cb528579b34e7828e681c8a6f32fbef7c.

**Comment by galdiuz** [comment]
Please add a new version to the NPM package, the latest version (3.6.2) still generates code with the typo.

**Comment by dillonkearns** [comment]
👍 the NPM package is now live: https://www.npmjs.com/package/@dillonkearns/elm-graphql/v/4.0.0 

https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-NPM-PACKAGE.md#400---2019-12-17
