### ISSUE TITLE
Ignoring the Type of an Error

### ISSUE THREAD

**Issue by Jayshua** [dillonkearns/elm-graphql#224]
I have an endpoint which returns a `Maybe Account`. If I get a `Just` I need to show the page and if I get a `None` I need to redirect to another page. It looks like this:

```elm
            case result of
                Ok Nothing ->
                    (model, Route.navigateTo navigationKey (Route.Login Route.MyAccount))

                Ok (Just account) ->
                    ({model | account = Updateable.fromResult (Ok account) model.account}, Cmd.none)

                Err err ->
                    ({model | account = Updateable.fromResult (Err err) model.account}, Cmd.none)
```

The problem is that my model stores just an `Updateable Account` not an `Updateable (Maybe Account)` and the `Updateable` type also stores the error as a `Graphql.Http.Error Account`  - expecting it to have the same type as the regular value. Meaning the last case fails because I need to map the error to contain an `Account`, but the type I'm trying to map it from is a `Maybe Account` so I may not have an `Account` to map it into.

I'm not sure how the errors are implemented in elm-graphql, but I was thinking this function could help:

```
dropError : Result (Error decodesTo) decodesTo -> Result (Error a) decodesTo
```

This is similar to `discardParsedErrorData` but rather than replacing it explicitly with the Unit, it replaces it with an unconstrainted type variable. This is kind of like the `never` function I think.

**Comment by Jayshua** [comment]
So I wrote a function to do this. Haven't worked out whether I can move the `never` function into the case instead of calling `Result.mapError`. If you're interested in including this function I can put together a pull request.

```
discardError : Result (Error decodesTo) decodesTo -> Result (Error a) decodesTo
discardError result =
    Result.mapError (mapError never) <|
        case result of
            Ok data ->
                Ok data

            Err (HttpError httpError) ->
                Err (HttpError httpError)

            Err (GraphqlError (GraphqlError.ParsedData parsed) errorList) ->
                Err (GraphqlError (GraphqlError.UnparsedData Json.Encode.null) errorList)

            Err (GraphqlError (GraphqlError.UnparsedData value) errorList) ->
                Err (GraphqlError (GraphqlError.UnparsedData value) errorList)
```

**Comment by dillonkearns** [comment]
Smart idea! I didn't think to do that, but that's exactly what people would want this function to do.

I would welcome a PR on this, that would be great. Thanks for sharing this @Jayshua!

**Comment by Jayshua** [comment]
Sure! Might be a day or two before I get to it. Should I replace discardParsedErrorData or add a new function?

**Comment by dillonkearns** [comment]
It'll be a breaking change, but I think it's still the right call to replace `discardParsedErrorData` here. There's never a reason someone would want the type to specifically be hardcoded to `()`, and I don't mind doing the breaking change to reduce the API cruft a little 👍 

No rush! And thank you!

**Comment by dillonkearns** [comment]
Thanks again for your feedback and work on this @Jayshua! This is a great refinement 👍

**Comment by Jayshua** [comment]
@dillonkearns As I've adjusted my code style for this, I've found myself needing `Error decodesTo -> Error a` more than I've needed `Result (Error decodesTo) decodesTo -> Result (Error a) decodesTo`. Probably because a lot of my mutations return a result themselves, so the selection ends up looking like this:

```
Result (Error (Result MutationError MutationResult)) (Result MutationError MutationResult)
```

Which I then usually case on to unify the result types:

```
case result of
   Ok (Ok successData) ->
      { model | result = Ok successData }
   Ok (Err error) ->
      { model | result = Err (UpdateError error) }
   Err error ->
      { model | result = Err (NetworkError (discardErrorData error)) }
```

Any thoughts on that?
