### ISSUE TITLE
Custom codecs for enums

### ISSUE THREAD

**Issue by galdiuz** [dillonkearns/elm-graphql#237]
Would it be a possibility to generate custom codecs for enums in a similar way as is currently possible for scalars? We have found that we already have custom implementations for some types in Elm that have the same functions that can be found in the generated enum types (i.e. a union, fromString, toString, decoder), and having to map from the generated enum type to our own type is not only inconvenient, but also produces unnecessary filesize bloat (especially for enums with a large amount of values).

**Comment by dillonkearns** [comment]
It sounds like you have an existing decoder that decodes values into an Enum. In that case, the case statement won't be automatically updated if your Enum type changes, right? So if I had that in my code, I would want to move away from using it to make sure that I don't have any out-of-sync decoding in the future.

Given my current understanding of this use case and proposed functionality, I'm reluctant to add this, especially given that the custom codec developer experience has a big overhead in terms of complexity for the users to learn (and for maintenance of the CLI tool as well).

**Comment by galdiuz** [comment]
You are correct that the case statement would not update should the Enum values in the schema change, and writing a test to validate that is complicated in many ways. With that and your other observations in mind I agree that it is probably better not to implement such functionality, or at least not in the way I proposed.

For others who might read this and are in the same situation, our "solution" to this was to replace our Enums with Scalars. This lets us use our own Elm types, we can decode directly into these types by using scalar codecs, and by implementing the same type validation as in Elm in our GraphQL server we guarantee that the server never outputs invalid values. While this means that you lose the ability to see a list of valid values when doing schema introspection, it removes the need to map from the generated types to our own.

**Comment by dillonkearns** [comment]
Hey @galdiuz, thanks for the update. I'm glad you found a workaround that gives you what you're looking for. And thanks for understanding.

Given this part of the `elm-graphql` philosophy, which is really core goal of the project:
> 1. Gives you type-safe GraphQL queries (if it compiles, it's valid according to the schema)

I don't think that behavior like this would be inline with the project's philosophy. Type-safety comes first and foremost, I think. I'm glad that you've found something that gives you what you're looking for as well!

Best regards,

Dillon
