### ISSUE TITLE
Graphql.Http.withOperationName argument order

### ISSUE THREAD

**Issue by galdiuz** [dillonkearns/elm-graphql#254]
The definition of [Graphql.Http.withOperationName](https://github.com/dillonkearns/elm-graphql/blob/4.5.0/src/Graphql/Http.elm#L191) is currently `Request decodesTo -> String -> Request decodesTo`, but it should probably be changed to `String -> Request decodesTo -> Request decodesTo` so that it's possible to chain it like the documentation for the function suggests:
```elm
query
    |> Graphql.Http.queryRequest "https://api.github.com/graphql"
    |> Graphql.Http.withOperationName "HeroNameAndFriends"
    |> Graphql.Http.send (RemoteData.fromResult >> GotResponse)
```
With the current definition you would have to do this:
```elm
query
    |> Graphql.Http.queryRequest "https://api.github.com/graphql"
    |> \request -> Graphql.Http.withOperationName request "HeroNameAndFriends"
    |> Graphql.Http.send (RemoteData.fromResult >> GotResponse)
```

**Comment by dillonkearns** [comment]
Thank you for reporting this! I pushed a fix:

https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-ELM-PACKAGE.md#500---2019-12-16
