### ISSUE TITLE
Function OptionalArgument.presentIf discussion

### ISSUE THREAD

**Issue by romariolopezc** [dillonkearns/elm-graphql#264]
Hello Dillon,

What do you think of having:
```elm
module Graphql.OptionalArgument ...


presentIf : (a -> Bool) -> a -> OptionalArgument a
presentIf checkerFn a =
    if checkerFn a then
        OptionalArgument.Present a

    else
        OptionalArgument.Absent
```

And use it like:
```elm
description = OptionalArgument.presentIf (not << String.isEmpty) form.description
```

What I'm thinking is that I don't know if the usage is going to rely more on negative or positive conditions, we can have `.presentIf` and/or `.absentIf`. I don't know if we should scope it to just one or the other or have both.

What do you think?

**Comment by dillonkearns** [comment]
I think I'd find it more intuitive to turn it into a `Maybe` and then use `fromMaybe`:

```elm
description =
  form.description
  |> nonEmptyStringOrNothing
  |> OptionalArgument.fromMaybe

nonEmptyStringOrNothing string =
  if String.isEmpty then
    Nothing
  else
    string
```

Similar to the `Result` helper we discussed, I would find this code easier to process mentally because I can understand each piece intuitively.

**Comment by dillonkearns** [comment]
Thanks for giving the concrete code snippets so it's easier to discuss!

**Comment by romariolopezc** [comment]
Oh man that `.fromMaybe` is powerful jajaja, yes I have a similar helper in my codebase. 

I just thought to share and discuss if it makes sense to include it in the core, maybe it would be nice to add some examples in the wiki on how to build those helpers and use function composition to get nicer code when using `OptionalArguments`

**Comment by dillonkearns** [comment]
Yeah, I think adding some examples to the docs would be really great! I'm all for PRs to add some more examples to the docs for `fromMaybe`! 😄 Or the docs could also be added to `OptionalArgument` at the top-level of that module documentation. I'll close this and we can follow up with doc changes in a separate thread. Thanks Romario!

**Comment by romariolopezc** [comment]
Thank you! This `elm-graphql` package is awesome!!

**Comment by dillonkearns** [comment]
Aww, thanks Romario! ❤️
