### ISSUE TITLE
Example in OptionalArgument docs might be wrong

### ISSUE THREAD

**Issue by iuliaL** [dillonkearns/elm-graphql#281]
I noticed this in the examples. 

https://github.com/dillonkearns/elm-graphql/blob/c95c3daceaa713b3a346ad804565461546213980/src/Graphql/OptionalArgument.elm#L23

and I guess it should be
`import Graphql.OptionalArgument exposing (OptionalArgument(..))`

👍 Danke

**Comment by dillonkearns** [comment]
Thank you!
