### ISSUE TITLE
Spec-legal GQL schema prevents codegen from completing

### ISSUE THREAD

**Issue by aaronwhite** [dillonkearns/elm-graphql#285]
The following schema is legal:

```
type Mutations {
  _: Boolean
}
```

However it causes the codegen to stall forever (presumably trying to find a suitable elm name?)

In any event, this is a trick used by schemas to help fragment schema files on the backend, and define a single, nearly empty root Mutation/Queries object(s) (empty would be illegal, hence the dummy field)

**Comment by dillonkearns** [comment]
This is fixed with NPM package version 4.0.2 👍 https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-NPM-PACKAGE.md#402---2020-03-04

Thank you for reporting the issue Aaron! 🙏
