### ISSUE TITLE
Pagination API Brainstorm

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-graphql#29]
I would like to collect use cases and ideas about pagination helpers in `dillonkearns/graphqelm`. I made a simple concrete example that does basic pagination using the Github API: [`examples/src/GithubPagination.elm`](https://github.com/dillonkearns/graphqelm/blob/master/examples/src/GithubPagination.elm).

Here is some reference material:

Facebook's [Relay Connections Cursor Specification](https://facebook.github.io/relay/graphql/connections.htm) - this describes the standard format for pagination in GraphQL.
[Post from Apollo blog on understanding connections](https://dev-blog.apollodata.com/explaining-graphql-connections-c48b7c3d6976) - this explains it in more practical terms.

Apollo has a `fetchMore` function, but it may not be so relevant in the context of Elm because of the very different way of performing side-effects and using types:
https://www.apollographql.com/docs/react/recipes/pagination.html
Here's a [blog post describing pagination with Apollo](https://dev-blog.apollodata.com/pagination-and-infinite-scrolling-in-apollo-client-59ff064aac61).

In my example code at the top of this post, it seems fairly straightforward without any helper functions and it's hard to imagine helper functions making it easier. I may be missing something or not accounting for some use cases, though. I'd love to hear other people's ideas on how pagination could be made simpler with helper functions or generated code.

**Comment by pzingg** [comment]
Whatever you choose, please make it compatible with Elixir's Absinthe.Relay server side implementation. https://github.com/absinthe-graphql/absinthe_relay

**Comment by dillonkearns** [comment]
Good idea, I'll use that in my experiments thanks @pzingg :-)

**Comment by dillonkearns** [comment]
Closing this for now to reduce noise. I'll refer back to this thread when I consider this issue more.

**Comment by dillonkearns** [comment]
Hello @Maxim-Filimonov! Yes, those are along the lines I was thinking as well. I took a working example of pagination and played around with turning it into a nice API that could be generated for APIs that follow the Relay Connections Spec. I'm happy with what I have so far! https://github.com/dillonkearns/elm-graphql/pull/113

**Comment by dillonkearns** [comment]
I'm going to close this issue out and let any feedback on my current design happen on #113. Any feedback is welcome there. Thanks!
