### ISSUE TITLE
Shadowing issue in generated code

### ISSUE THREAD

**Issue by albertdahlin** [dillonkearns/elm-graphql#297]
Interfaces can cause a shadowing issue in the generated code if they contain a field called `selections`.

Graphql schema example:
```graphql
interface Test {
    selections : String
}
```

The generated code will look like:

```elm
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Generated.Interface.Test
fragments selections =
    ...


selections : SelectionSet String Generated.Interface.Test
selections =
    ...
```

The compiler will complain:
```
The name `selections` is first defined here:

66| selections =
    ^^^^^^^^^^
But then it is defined AGAIN over here:

33| fragments selections =
              ^^^^^^^^^^
Think of a more helpful name for one of them and you should be all set!

```

**Comment by dillonkearns** [comment]
I published a fix for this in NPM package version 4.2.0. Thank you for the report!

https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-NPM-PACKAGE.md#420---2021-02-05
