### ISSUE TITLE
Command line error: "elm-graphql: command not found"

### ISSUE THREAD

**Issue by Samuelote** [dillonkearns/elm-graphql#298]
I'm just trying to boot up the example of this project that's on the README. I've successfully ran and installed `
npm install --save-dev @dillonkearns/elm-graphql
` but I keep getting the error of `elm-graphql: command not found` when I run `elm-graphql https://elm-graphql.herokuapp.com --base StarWars --output examples/src
`.

I'm probably doing something stupid but I can't quite figure it out. Any ideas?

**Comment by Jayshua** [comment]
`npm install ...` will install the package locally, not globally. Locally installed packages require a more complex invocation to run. I recommend using npx which I think is packaged with node these days. Something like `npx elm-graphql ...`.

Alternatively you can use `npm install -g ...` which will install the package globally and put it in your `PATH` so it can be run directly from the command line like you showed.

**Comment by dillonkearns** [comment]
Yeah, what @Jayshua said is right. Also, what's your goal in trying to run it in the example folder?

You can see how the commands are run in this script:

https://github.com/dillonkearns/elm-graphql/blob/master/bin/approve#L17

In the case of that script, it's running it with a global install, but you could accomplish a similar thing with npx.

**Comment by Samuelote** [comment]
Thank you guys. When I prepend npx to the front of the command, it seems to run fine. :)

@dillionkearns Honestly, that comes down to my own negligence, as I just wanted the elm-graphql command to work. I wasn't worried so much about the rest of the command (ie the output). 

Thanks again and I'm stoked to dive into this package.
