### ISSUE TITLE
Error interfacing with Hasura - Introspection query fails

### ISSUE THREAD

**Issue by opvasger** [dillonkearns/elm-graphql#337]
I opened this issue, as I've had a problem using `elm-graphql` with  the `hasura graphql-engine`. I'm not sure if this is my mistake, or has to do with either repo, but I figured you'd want a heads-up as well @dillonkearns!

The introspection-query generated by `elm-graphql` includes a `isDeprecated` query-variable:
```
elm-graphql https://XYZ.ABC/v1/graphql --base Hasura --output build --header x-hasura-admin-secret:XYZABC
```
I've tried the `--exclude-deprecated` flag aswell, but the query variable is still sent along with the query, which fails it.

a note on Hasura, the graphql-engine I'm trying to introspect (in this case as part of my AWS CodeBuild-setup): Hasura has a feature to reload metadata in their WEB GUI. If I reload metadata, and run the query WITH the query-variable, it works the 1st time, but fails every subsequent introspection. This has lead me to think that Hasura might have a bug - more about in the link below.

https://github.com/hasura/graphql-engine/issues/4547

**Comment by dillonkearns** [comment]
Hey @opvasger, thank you for brining it to my attention! It looks like this has been fixed and released on the Hasura-side, which is excellent 🎉

I'll close this, but if anything else comes up feel free to re-open or create a new issue. Thank you!
