### ISSUE TITLE
Consider more vertical formatting

### ISSUE THREAD

**Issue by sporto** [dillonkearns/elm-graphql#343]
I often open generated files to see the types that functions use.

An example of a generated function in our code looks like:

```
evaluableRules_RequestResourceReport : EvaluableRulesRequestResourceReportRequiredArguments -> SelectionSet decodesTo Api.Object.EvaluableRules_RequestResourceReportPayload -> SelectionSet (Maybe decodesTo) RootMutation
```

There is a lot of horizontal scrolling to do in order to read the types in the functions.

It would be really nice if the generated code could insert line breaks so elm-format will render function signatures like:

```
evaluableRules_RequestResourceReport :
    EvaluableRulesRequestResourceReportRequiredArguments
    -> SelectionSet decodesTo Api.Object.EvaluableRules_RequestResourceReportPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
```

This would make inspecting these files much easier. Thanks.

**Comment by dillonkearns** [comment]
I would welcome a PR to use vertical spacing for the formatting. I've got a few other priorities I'm focused on for my open source work right now, though, so this won't make it to the top of my queue in the near future.
