### ISSUE TITLE
Generate example as function documentation

### ISSUE THREAD

**Issue by berenddeboer** [dillonkearns/elm-graphql#380]
Related to #296 I think it would be great of the header of a function (module) has some samples.

I also struggled initially with creating the right code. Luckily with Elm once it compiles it works, but getting it to compile was a bit of a struggle. This is some code I copied from a project:

```elm
queryPage
    (\sectionOptionals ->
        { sectionOptionals
            | locale = Present locale
            , filter =
                Present
                    (buildPageModelFilter
                        (\menuItemFilter ->
                            { menuItemFilter
                                | menuItem =
                                    Present (linkFilter itemId)
                            }
                        )
                    )
        }
    )
```
Writing GraphQl with Elm isn't trivial to figure out.

The example doesn't need to be exhaustive, just the minimal to compile (i.e. with the most basic options), and perhaps an example with more difficult options.

But this is probably not trivial to add.

**Comment by dillonkearns** [comment]
Hey, thanks for the feedback. This sounds like a lot of work for something that isn't quite where I want to focus my efforts. I'm actually working on some contributions to intellij-elm, and I know some cool features are also being added to the Elm language server implementation. That's more where I envision working to make improvements to this workflow. If we have better editor support, like completions that are more type-aware, and field completions within the context of a record that know which fields are available, I think it will make the experience of writing elm-graphql queries a lot nicer. Ultimately, these are language tooling features that will make the whole community stronger, and they will have a lasting impact on the Elm experience.

A feature like this could be cool, but it would be a lot of work and it's not something I plan to work on. I'll close this issue, but if you're inclined to work on something like this PRs are welcome.
