### ISSUE TITLE
missing script: build-gql

### ISSUE THREAD

**Issue by dotnetspec** [dillonkearns/elm-graphql#395]
Hi,

Thanks for the module which is very useful.
My setup:
node version: 11.10.0
npm version: 6.7.0
elm version: 0.19.1
VSCode|About:
```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.10.0-38-generic
```

I'm attempting to use it in a tutorial:
[https://dev.to/xeticode/faunadb-graphql-and-elm-a-tutorial-for-jamstack-part-2-2eec](url)
I installed the module into the base directory of my project with
```
elm install dillonkearns/elm-graphql
```
initially, and then with:
```
npm i @dillonkearns/elm-graphql
```
Although both ways 'installed successfully', in both cases attempting to run:
```
FAUNA_KEY=<fuana-server-key> npm run build-gql
```
with a valid server key, as per the tutorial, I get:
```
missing script: build-gql
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     build
```
It appears the installation somehow missed adding the script to package.json.
I also tried running the script directly:
```
npx elm-graphql https://graphql.fauna.com/graphql --base <myprojectname> --output src --header \"authorization: Bearer ${FAUNA_KEY}\"
```
and got:
```
No matching optionsParser...
```
What can I do to fix this so that 
```
FAUNA_KEY=<fuana-server-key> npm run build-gql
```
runs correctly in my project?
Thanks ...
[2020-09-16T09_03_23_154Z-debug.log](https://github.com/dillonkearns/elm-graphql/files/5231297/2020-09-16T09_03_23_154Z-debug.log)

**Comment by dillonkearns** [comment]
`build-gql` is a script that the specific project defined it sounds like. But it would use something along the lines of your `npx elm-graphql` command there.

It seems like there might be a problem with the escaping in front of your quote characters. See this example from the elm-graphql readme:

```shell
elm-graphql https://elm-graphql.herokuapp.com --base StarWars --output examples/src --header 'headerKey: header value'
```

**Comment by dotnetspec** [comment]
Thanks for your prompt response Dillon - that fixed it.
Note for anyone else - had to ensure the regex was valid for 'base'. Found this useful to debug the line:
[https://regex101.com/debugger](url)
