### ISSUE TITLE
Handling GQLHttp.send

### ISSUE THREAD

**Issue by dotnetspec** [dillonkearns/elm-graphql#410]
Essentially the problem appears, to me, to revolve around the fact that a List of String (username and password) is going out to Faunadb and a single string (the token) should be returned from faunadb and then handled.
(SR.Types.Token is a String type).
After running the "build-gql" script I get the following Elm compiler error:
```
Something is off with the body of the `queryLoginUser` definition:
30| Query.loginUser requiredArgs
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
This `loginUser` call produces:
SelectionSet (List String) RootQuery

But the type annotation on `queryLoginUser` says it should be:
SelectionSet SR.Types.Token RootQuery
```

This is the generated code in Query.elm:
```
type alias LoginUserRequiredArguments =
{ username : String
, password : String
}

loginUser : LoginUserRequiredArguments
-> SelectionSet (List String) RootQuery
loginUser requiredArgs =
Object.selectionForField "(List String)" "loginUser" [ Argument.required "username" requiredArgs.username Encode.string, Argument.required "password" requiredArgs.password Encode.string ] (Decode.string |> Decode.list)
```
Does `(Decode.string |> Decode.list) `refer to the list going out?
However, the schema defines loginUser as:
`loginUser(username: String!, password: String!): String! @resolver(name: "login_user")`
i.e. it returns a String (not a list).
Why is elm-gql generating code for a List to be returned when the schema specifies a String? 
I have edited the Query.elm file to expect a String and it 'works' for the purpose of obtaining a token, however:

- I shouldn't be editing the Query.elm file as per note at the top of that file.
- I would have to re-edit it each time I updated the files with elm-gql, so it is anyway not satisfactory to do that and I should understand and resolve the issue correctly.

1. Do you know what is happening to cause this (seemingly incorrect code generation)?
2. Or otherwise, what am I misunderstanding that's leading to the problem?
3. What should I do to fix?

thanks ...

**Comment by dillonkearns** [comment]
Hello!

It's hard to say from the context here, and it's a lot of context to dig through. I would start by looking at what information the introspection schema is returning. One thing that can happen is that you could be working with an outdated schema, so that's one thing to check for.

If you give me a reproducible minimal reproduction of this issue then I'd be happy to take a look. There are some instructions on that here: https://github.com/dillonkearns/elm-graphql/tree/master/reproducing-issues. I think you're likely to find that it's not related to the elm-graphql code generation, but if you do find it to be an elm-graphql issue and give me a minimal reproduction then I'll gladly fix it 👍

**Comment by dillonkearns** [comment]
Hello, I tried reproducing this from the information above and I wasn't able to. Here's what I tried:


I added this line to https://github.com/dillonkearns/elm-graphql/blob/5da8de69192269cd9c6cbe5a8bcf09871c785bb0/ete_tests/edge-cases.gql#L15.

```diff
type RootQueryType {
  hello(name: String!): String!
+  loginUser(username: String!, password: String!): String!
}

```

Then I saw it generated this code:

```elm
type alias LoginUserRequiredArguments =
    { username : String
    , password : String
    }


loginUser :
    LoginUserRequiredArguments
    -> SelectionSet String RootQuery
loginUser requiredArgs =
    Object.selectionForField "String"
        "loginUser"
        [ Argument.required "username" requiredArgs.username Encode.string
        , Argument.required "password" requiredArgs.password Encode.string
        ]
        Decode.string
```

Everything compiled, and the new generated code has no mention of lists anywhere. Could you please send me a reproducible example?

The easiest way to set this up is to either tweak the schema in the `edge-cases.gql` file I refered above after cloning the `elm-graphql` repo, or to get your current GitHub schema as SDL (schema definition language) and see if you can reproduce it from that. Then if you're willing, you can send me that, or you can try to remove the pieces until you get the minimal reproducible scenario. Thank you!

**Comment by dotnetspec** [comment]
Hi Dillon,
Thank you very much for your attention to this issue. As you mentioned there is a lot of context. I have switched focus to data modelling in Fauna itself and that, in turn, affects the code that is generated with elm-gql. Unfortunately, I'm currently resolving fundamental issues, like schema upload, in that realm too. I would like to be reasonably confident as to the db setup to minimize the extent to which I need to keep switching environments and focus.
I will return to this issue and properly address your feedback as soon as possible ...

**Comment by dotnetspec** [comment]
FYI, as an update: I apologize for the time it is taking me to either provide the information requested or close this issue. As mentioned previously I switched to resolving Fauna related issues and that has resulted in a new schema and hence new compilation issues in Elm [which I am attempting to resolve in this repository as well.](https://github.com/dillonkearns/elm-graphql/issues/496) 
However, addressing the Fauna issues was time consuming for one reason or another.

Without compilation, at least, in Elm I feel unable to return to fully addressing/resolving this issue. It is possible I have already and I forgot to update here. So, the point, at this stage, is that closing this issue is dependent on those issues that are currently preventing compilation.

**Comment by dillonkearns** [comment]
I'll close this for now, but if at some point there's some more context and someone can share a reproducible case, please do share it and re-open the issue!
