### ISSUE TITLE
Extra 'query' in request

### ISSUE THREAD

**Issue by bobvandenberge** [dillonkearns/elm-graphql#416]
Hi - i'm testing the library for a new project but can't get it to work. Just wondering if I'm doing something wrong. 

Backend: Kotlin with https://github.com/ExpediaGroup/graphql-kotlin
Frontend: Clean elm project with only elm-graphql. (See code below)

I'm trying to do a regular query, but in the http request that get's generated, there are 2 'query' listings. One for the property and then 1 in the request itself
```
{"query":"query {\n  getEventsForWeek3563716064: getEventsForWeek(week: 44) {\n    name3832528868: name\n    amountOfCoaches1207450440: amountOfCoaches\n  }\n}"}
```

The Kotlin API doesnt accepts this, it excepts the following: 
```
{"query":"{\n  getEventsForWeek3563716064: getEventsForWeek(week: 44) {\n    name3832528868: name\n    amountOfCoaches1207450440: amountOfCoaches\n  }\n}"}
```

Is there a way to remove this extra query before the opening bracket `{` ?

Code used to build the request: 
```elm
module Main exposing (..)

import Browser
import GeneratedApi.Query exposing (getEventsForWeek)
import GeneratedApi.Object.Event as Event
import Graphql.Http
import Graphql.Operation exposing (RootQuery)
import Graphql.SelectionSet as SelectionSet exposing (SelectionSet)
import Html exposing (Html, div, text)
import RemoteData exposing (RemoteData(..))


-- MAIN


main =
  Browser.element { init = init, view = view, update = update, subscriptions = subscriptions}

type alias Response =
    List Event

type alias Event =
    {
        name: String
        , amountOfCoaches: Int
    }

-- MODEL

query : Int -> SelectionSet Response RootQuery
query weekNumber =
    getEventsForWeek {week = weekNumber} <|
        SelectionSet.map2 Event
            Event.name
            Event.amountOfCoaches

makeRequest : Cmd Msg
makeRequest =
    44
        |> query
        |> Graphql.Http.queryRequest "http://localhost:8080/graphql"
        |> Graphql.Http.send (RemoteData.fromResult >> GotResponse)

-- UPDATE


type Msg
  = GotResponse Model

type alias Model =
    RemoteData (Graphql.Http.Error Response) Response

init : () -> ( Model, Cmd Msg )
init _ =
    ( RemoteData.Loading, makeRequest )

update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        GotResponse response ->
            ( response, Cmd.none )


-- VIEW


view : Model -> Html Msg
view model =
  case model of
      NotAsked ->
        div []
            [ text "NotAsked!" ]

      Loading ->
        div []
            [ text "Loading!" ]

      Failure e ->
        div []
            [ text "Failure!" ]

      Success a ->
        div []
            [ text "Succes!" ]


-- SUBSCRIPTIONS
subscriptions : Model -> Sub Msg
subscriptions model =
  Sub.none

```

**Comment by dillonkearns** [comment]
Hello,

I couldn't find where this is formally written up in the spec, but I see references to other widely used libraries that have the same format, like here: https://www.apollographql.com/docs/apollo-server/v1/requests/#post-requests.

```json
{
  "query": "query aTest($arg1: String!) { test(who: $arg1) }",
  "operationName": "aTest",
  "variables": { "arg1": "me" }
}
```

GraphQL queries allow you to put the operation name `query` in front, or you can leave it out. You can also put `mutation` there. If you can't put the type of operation in front there, then how would you perform a mutation using this library?


From this page, https://graphql.org/learn/serving-over-http/, I see this note:

> If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

Could it be that this Kotlin library is expecting you to send that application type, or something else? I think you'll have to do some more investigation or open an issue with the Kotlin library to understand what they're expecting on their end.

**Comment by bobvandenberge** [comment]
Alright - found the issue. 

Apparently (not sure why) the issue was caused because of invalid CORS headers in the backend. Because of that the OPTION request failed which screwed up a lot of other things. 

Thanks @dillonkearns for pointing me to the mutations, that led me to this solution.

**Comment by dillonkearns** [comment]
Ah yes, that's quite a common one. Glad you figured out the problem! Thanks for reporting back.
