### ISSUE TITLE
Compile error after running generator and importing

### ISSUE THREAD

**Issue by atomkirk** [dillonkearns/elm-graphql#421]
I've seen two compiler errors, the first one is this, after trying to create this demo project for you:

```
-- MODULE NOT FOUND --------------- /Users/adamkirk/Work/forks/demo/my-elm-spa/src/Demo/Scalar.elm
You are trying to import a `Graphql.Codec` module:
7| import Graphql.Codec exposing (Codec)
          ^^^^^^^^^^^^^
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?
    GraphQLClient
    Graphql.Field
    Graphql.Http
    Graphql.Document
Hint: If it is not a typo, check the "dependencies" and "source-directories" of
your elm.json to make sure all the packages you need are listed there!
```

The second is on a real project, which I think will happen in this project as well once once the Codec error is fixed. Here is the second error:

```
-- TYPE MISMATCH --------------- /Users/adamkirk/Work/mt/markable/web-elm/src/Markable/InputObject.elm
This function cannot handle the argument sent through the (|>) pipe:
355|         [ ( "geometry", (Encode.float |> Encode.maybe |> Encode.maybe |> Encode.list |> Encode.list) |> Encode.optional input.geometry ), ( "kind", Encode.string |> Encode.optional input.kind ) ]
                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The argument is:
    List (List (Maybe (Maybe Float))) -> Value
But (|>) is piping it to a function that expects:
    List (Maybe (List (Maybe Float))) -> Value
```

I'm pretty sure the issue is dealing with lists of lists of floats in the mutation. I have a list of lists in a query and that compiles fine, its just this list of lists for a mutation. Plus, when I changed it from `list_of(list_of(:float))` to a list of objects:

![image](https://user-images.githubusercontent.com/2091439/99298657-4a380700-2807-11eb-8b8d-6e56e8d5cdda.png)

I'd prefer to keep it a list of lists, simply because these data structures have a lot of coordinates and it saves space to transmit and save them as a list of lists rather than a list of objects.

Heres is the demo monorepo that provides an absinthe backend and elm-spa frontend to reproduce:
[demo.zip](https://github.com/dillonkearns/elm-graphql/files/5549192/demo.zip)

**Comment by atomkirk** [comment]
[demo.zip](https://github.com/dillonkearns/elm-graphql/files/5550374/demo.zip)

Ok, this reproduces the issue. This contains the `sdl.js`file as well.

If you download this, unzip it, cd in and run `elm make src/Main.elm --debug --output=public/dist/elm.compiled.js` you'll see the compiler error.

```
Detected problems in 1 module.
-- TYPE MISMATCH --------------------------------------- src/Api/InputObject.elm

This function cannot handle the argument sent through the (|>) pipe:

355|         [ ( "kind", Encode.string |> Encode.optional input.kind ), ( "geometry", (Encode.float |> Encode.maybe |> Encode.maybe |> Encode.list |> Encode.list) |> Encode.optional input.geometry ) ]
                                                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The argument is:

    List (List (Maybe (Maybe Float))) -> Value

But (|>) is piping it to a function that expects:

    List (Maybe (List (Maybe Float))) -> Value
```

**Comment by dillonkearns** [comment]
Hello! Thanks for the reproducible example.

The `Graphql.Codec` import error seems like a setup issue (because that module is part of the published package: https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-Codec). I'm guessing on the first attempt you didn't `elm install dillonkearns/elm-graphql`.

The other error seems like a bug. I narrowed down the SDL and made a script to rerun it.

It looks like it is currently generating this:

```elm
        , ( "geometry"
          , (Encode.float
                |> Encode.maybe
                |> Encode.maybe
                |> Encode.list
                |> Encode.list
            )
                |> Encode.optional input.geometry
          )
```

But it should be generating this:

```elm
        , ( "geometry"
          , (Encode.float
                |> Encode.maybe
                |> Encode.list
                |> Encode.maybe
                |> Encode.list
            )
                |> Encode.optional input.geometry
          )
```

I'll take a look, it may be an issue with how List/Maybe values interact. Thanks for reporting the problem!

**Comment by dillonkearns** [comment]
I pushed the repo with the reproduction steps: https://github.com/dillonkearns/elm-graphql-input-object-bug.

**Comment by atomkirk** [comment]
Rad! Thank you!
