### ISSUE TITLE
Enhancement - Add support for Dgraph

### ISSUE THREAD

**Issue by mrlorx** [dillonkearns/elm-graphql#507]
It would be very nice to have a direct support for the [Dgraph](https://dgraph.io/) Database and their DGQL query language.
I'm very new to Elm and also to Dgraph, so I can't offer any help or further information, but it would be nice to see these two working together.
I know this is a big one, but you may take a look at it.

**Comment by dillonkearns** [comment]
Hey, Dgraph has come up a few times. I'm open to discussing what supporting directives might look like in `elm-graphql` (see #482 for a discussion on collecting use cases for that). However, anything that's not in the GraphQL spec or applicable to GraphQL in general is out of scope for my goals for this project. So for anything beyond that, I would say realistically the best path for something like that would be to potentially fork this project or create a new project if somebody has the motivation to take on something like that.

I'd definitely be curious to hear more about Dgraph, and I think it would be helpful for reference to enumerate any ways where `elm-graphql` does and does not support making requests for to Dgraph server. But I want to be realistic about what to expect for features and what's in scope for this project, so I'll close this issue.

Feel free to enumerate anything for reference here that might be helpful for Dgraph users to understand what `elm-graphql` does or does not support, that would be very helpful to understand.
