### ISSUE TITLE
Clarify on imports in the Gitbook

### ISSUE THREAD

**Issue by mradke** [dillonkearns/elm-graphql#58]
I was a little bit lost when reading the [Gitbook](https://dillonkearns.gitbooks.io/elm-graphql/content/selection-sets.html) since I wondered where the `with` function came from.

Of course I had just skimmed over the first article and hence was confused where we imported `with`. I think the main source of my confusion stemmed from the fact that the `identity` function was described in detail but nothing could be found for `with` on the linked page.

Clearly one can look it up in the (awesome) [docs](http://package.elm-lang.org/packages/dillonkearns/graphqelm/latest) but I think this could be a bit hindering for newcommers.

Anyways, not a high priority. Just wanted you to know 😃 
Thanks for the awesome library! 👍

**Comment by dillonkearns** [comment]
Just doing some housekeeping. For now the docs live mostly in https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-SelectionSet and in the examples/ folder, and the Gitbook is no longer the best place to get information so I'll close this issue for now. Thanks!
