### ISSUE TITLE
elm-graphql is still outputting Debug.toString when generating scalar debuggers.

### ISSUE THREAD

**Issue by obmarg** [dillonkearns/elm-graphql#68]
I'm trying to compile an app that uses elm-graphql 1.0.0 with elm 0.19 and `--optimize` but it's not compiling as some of my `Api.Object.*` modules have Debug.toString calls in them.

I see that 3720d8d02 was meant to swap these out for the 0.19 equivalents, but if I look in `dist/bundle.js` I can [still see the old Debug.toString implementation](https://github.com/dillonkearns/elm-graphql/blob/master/dist/bundle.js#L7620).  Has something gone wrong with the release?

**Comment by dillonkearns** [comment]
Hello @obmarg, I've pushed a fix for this! You'll need to update to Elm package version `1.1.0` and NPM package version `1.0.1`. Thanks again for reporting the issue!

**Comment by obmarg** [comment]
Awesome, thanks for the rapid fix @dillonkearns
