### ISSUE TITLE
Update Subscriptions Ellie example using external Phoenix transport code

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-graphql#70]
Now that the transport layer code has moved out of `dillonkearns/elm-graphql` based on #43, we should have an Ellie example linked to in the README to illustrate how this could be done (as [this comment points out](https://github.com/dillonkearns/elm-graphql/issues/43#issuecomment-415551013)).

This may have to wait until the elm/websocket package, and perhaps a package for Elm and Phoenix, are published. [This package](https://package.elm-lang.org/packages/slashmili/phoenix-socket/latest/) uses long polling with Phoenix as a workaround, but is listed as not being production ready yet so it might be best to hold off for now.

**Comment by knewter** [comment]
I'm setting it up right now with @absinthe/socket and ports, might be worth showing that off.

**Comment by dillonkearns** [comment]
@knewter yes please! I'd love to get a working example from you, and then I can update the Ellie example to use the same as pattern 👌👌

**Comment by knewter** [comment]
I'll release the underlying app open source in the next couple of weeks, but for now here's the general pattern: https://gist.github.com/knewter/6c95a14d03ad038db32f5e5c5852d800

**Comment by dillonkearns** [comment]
I am super grateful to you for sharing this, @knewter, thank you! I just got my subscriptions demo from 0.18 working locally. Now I just need to package it up so that I can post it as a live demo. I'll post an update here once I do and close this out 👍

**Comment by dillonkearns** [comment]
I published a live demo based on your example @knewter. Thank you so much for the help! I [linked to the demo and its source code in the README](https://github.com/dillonkearns/elm-graphql/commit/1738f8469344b99f005d4c54babe4fa75109fd33) so I think we can call this done. Please don't hesitate to follow up here or in slack if you have any suggestions for how to make the example or docs better. Thanks!
