### ISSUE TITLE
Feature request: generate Elm query code from GraphQL query format

### ISSUE THREAD

**Issue by dasch** [dillonkearns/elm-graphql#76]
Have you given any thought to supporting queries written in GraphQL itself?

For example, the `elm-graphql` compiler could parse this file:

```graphql
# queries/fetchComments.graphql`
query FetchComments($postId: Int!) {
  post(id: $postId) {
    comments {
      author {
        name
      }
      body
    }
  }
}
```

And generate an Elm file with the following signature:

```elm
fetchComments
  :  { postId : Integer }
  -> Task SomeError { post : { comments : List { author : { name : String }, body : String } } }
```

I think the GraphQL language is actually more concise and easy to use than an Elm DSL.

**Comment by dillonkearns** [comment]
Hello! Thanks for the request. I want to keep this library focused on building queries with an Elm DSL, in keeping with the design goals stated at the top of the Readme. But this is a perfectly reasonable approach for a different library to use. I believe that this library will do what you're looking for: https://github.com/harmboschloo/graphql-to-el. Cheers!
