### ISSUE TITLE
Find `elm-format` binary more reliably

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-graphql#91]
The code for finding the `elm-format` executable is unreliable and doesn't work in some environments. See the relevant code here:

https://github.com/dillonkearns/elm-graphql/blob/38860e67f38fc3d8777950fadee5e0d6812de12e/generator/src/formatted-write.ts#L4-L5
https://github.com/dillonkearns/elm-graphql/blob/38860e67f38fc3d8777950fadee5e0d6812de12e/generator/src/formatted-write.ts#L55-L63

It would be nice to find a way to reliably find the executable so that the `elm-format` step can be run for everybody.

**Comment by btorellALTA** [comment]
I'm having this issue on MacOS 10.13 High Sierra with a global install of `elm-format@0.8.1`. I'm running `elm-graphql` as an NPM script, like so:

```
...
scripts: {
    "api": "elm-graphql <my GraphQL server> --base Api --output elm/src"
}
...
```

**Comment by dillonkearns** [comment]
Thank you for providing those details @btorellALTA!

**Comment by BrianHicks** [comment]
random kibitzer here! What's wrong with using the system lookup mechanism, e.g. just calling `elm-format` directly? That would find it on `PATH`, wherever that actually shows up. If `elm-format` is not installed, you'd catch an ENOENT-style exception.

**Comment by BrianHicks** [comment]
`npx elm-format` will not work if someone installed elm-format without `npm`, will it? For example, both Homebrew and Nix have elm-format available.

In that case, it seems better to use the environment to do this in the standard way rather than try and do something fancy-but-breaking in the CLI.

Fortunately, `elm-format --elm-version {0.18,0.19}` exists. If you call it with an unsupported version (say `0.20`) it fails early and with a clear message, attached:

```
$ elm-format --elm-version 0.20 src/Main.elm
option --elm-version: Invalid Elm version "0.20".  Supported versions are 0.18, 0.19

elm-format 0.8.1

Usage: elm-format [INPUT] [--output FILE] [--yes] [--validate] [--stdin]
                  [--elm-version VERSION] [--upgrade]
{ … snip … }
```

It *seems* like that would address the concerns you had above? But maybe not?

(also I'm kibitzinggggg! Do what you think best, as always. ❤️)

**Comment by dillonkearns** [comment]
@Brianhicks your comments are much appreciated!

Now that you explain that, you're totally right that `npx` assumes that they have it installed locally... which is not very polite to have a hidden required dependency like that!

`elm-format` is listed as a dependency of the `@dillonkearns/elm-graphql` npm package... and what I really want to do, in an ideal world, is to point at that binary from the script! That would simplify things a lot. I'm having trouble googling it, I'm not sure if that's even possible or not... 🤔

**Comment by BrianHicks** [comment]
well, iff the CLI must be installed via npm, AND it's also a hard dependency (i.e. not a peer dependency) AND you can assume a sufficiently modern npm installation, then `npx` may make sense!

**Comment by JonRowe** [comment]
I'm also using a script in `package.json`:
```
  "scripts": {
    "format": "elm-format src/",
    "update_graphql": "elm-graphql 'http://0.0.0.0:4001/graphql' --header \"Authorization: Bearer $TOKEN\" --base App"
  },
```

**Comment by dillonkearns** [comment]
Hello all, thank you everyone for the excellent feedback! You all rock! 💯

It sounds like the `npx` route with [what NPM calls a peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) will solve the problem well. With the NPM peer dependency, `npm install` will tell you you need to add `elm-format` as a dependency before proceeding if it's not already there. We've got a working branch with this implemented: 

https://github.com/dillonkearns/elm-graphql/pull/87/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R43

I'll probably publish it today, unless I hear any strong disagreements. Thanks all!

**Comment by dillonkearns** [comment]
#87 has been merged! I'm feeling good about this solution. Please send me feedback if you run into any issues here, I think this should resolve the problem though 👍 Thanks all!

**Comment by dillonkearns** [comment]
`@dillonkearns/elm-graphql` version 1.0.8 is live on NPM!
